// <auto-generated />
using System;
using Global_Solution.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Global_Solution.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602015536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Global_Solution.Domain.Entities.AlertaEntity", b =>
                {
                    b.Property<int>("ID_ALERTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ALERTA"));

                    b.Property<int>("ID_AREA")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<int>("ID_LEITURA_GATILHO")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA_GATILHO");

                    b.Property<string>("MENSAGEM_ALERTA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM_ALERTA");

                    b.Property<string>("STATUS_ALERTA")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS_ALERTA");

                    b.Property<DateTime>("TIMESTAMP_ALERTA")
                        .HasColumnType("timestamp")
                        .HasColumnName("TIMESTAMP_ALERTA");

                    b.Property<string>("TIPO_ALERTA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("ID_ALERTA");

                    b.HasIndex("ID_AREA");

                    b.HasIndex("ID_LEITURA_GATILHO");

                    b.ToTable("SMAE_ALERTA");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.AreaRiscoEntity", b =>
                {
                    b.Property<int>("ID_AREA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_AREA"));

                    b.Property<decimal?>("AREA_ALAGADA_ALERTA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("AREA_ALAGADA_ALERTA");

                    b.Property<decimal?>("AREA_ALAGADA_EMERGENCIA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("AREA_ALAGADA_EMERGENCIA");

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("FONTE_DADOS")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FONTE_DADOS");

                    b.Property<decimal?>("LATITUDE")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("LONGITUDE")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("METODO_MEDICAO_EXTENSAO")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("METODO_MEDICAO_EXTENSAO");

                    b.Property<string>("METODO_MEDICAO_NIVEL")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("METODO_MEDICAO_NIVEL");

                    b.Property<decimal>("NIVEL_ALERTA_EMERGENCIA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_ALERTA_EMERGENCIA");

                    b.Property<decimal>("NIVEL_ALERTA_PREVENTIVO")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_ALERTA_PREVENTIVO");

                    b.Property<decimal?>("NIVEL_EVACUACAO")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_EVACUACAO");

                    b.Property<decimal?>("NIVEL_NORMAL_ESTACAO_CHUVA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_NORMAL_ESTACAO_CHUVA");

                    b.Property<decimal?>("NIVEL_NORMAL_ESTACAO_SECA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NIVEL_NORMAL_ESTACAO_SECA");

                    b.Property<string>("NOME_AREA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_AREA");

                    b.Property<string>("RESPONSAVEL_ATUALIZACAO")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("RESPONSAVEL_ATUALIZACAO");

                    b.Property<DateTime?>("ULTIMA_ATUALIZACAO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("ID_AREA");

                    b.ToTable("SMAE_AREA_RISCO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.InscricaoAlertaEntity", b =>
                {
                    b.Property<int>("ID_INSCRICAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_INSCRICAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_INSCRICAO"));

                    b.Property<int>("ID_AREA")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("RECEBER_EMAIL")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECEBER_EMAIL");

                    b.Property<int>("RECEBER_PUSH")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECEBER_PUSH");

                    b.Property<int>("RECEBER_SMS")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECEBER_SMS");

                    b.Property<DateTime>("TIMESTAMP_INSCRICAO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("TIMESTAMP_INSCRICAO");

                    b.HasKey("ID_INSCRICAO");

                    b.HasIndex("ID_AREA");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("SMAE_INSCRICAO_ALERTA");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.LeituraSensorEntity", b =>
                {
                    b.Property<int>("ID_LEITURA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_LEITURA"));

                    b.Property<string>("ID_SENSOR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<DateTime>("TIMESTAMP_LEITURA")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("TIMESTAMP_LEITURA");

                    b.Property<string>("UNIDADE_MEDIDA")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.Property<decimal>("VALOR_LEITURA")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_LEITURA");

                    b.HasKey("ID_LEITURA");

                    b.HasIndex("ID_SENSOR");

                    b.ToTable("SMAE_LEITURA_SENSOR");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.NotificacaoEntity", b =>
                {
                    b.Property<int>("ID_NOTIFICACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NOTIFICACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NOTIFICACAO"));

                    b.Property<string>("CANAL_ENVIO")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CANAL_ENVIO");

                    b.Property<int>("ID_ALERTA")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("STATUS_ENVIO")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS_ENVIO");

                    b.Property<DateTime>("TIMESTAMP_ENVIO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("TIMESTAMP_ENVIO");

                    b.HasKey("ID_NOTIFICACAO");

                    b.HasIndex("ID_ALERTA");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("SMAE_NOTIFICACAO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.SensorEntity", b =>
                {
                    b.Property<string>("ID_SENSOR")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<DateTime>("DATA_INSTALACAO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INSTALACAO");

                    b.Property<int>("ID_AREA")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AREA");

                    b.Property<string>("MODELO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("STATUS_SENSOR")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("STATUS_SENSOR");

                    b.Property<string>("TIPO_SENSOR")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_SENSOR");

                    b.Property<DateTime?>("ULTIMA_MANUTENCAO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_MANUTENCAO");

                    b.HasKey("ID_SENSOR");

                    b.HasIndex("ID_AREA");

                    b.ToTable("SMAE_SENSOR");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<DateTime>("DATA_CADASTRO")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("NOME_USUARIO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("SENHA_HASH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("TIPO_USUARIO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("SMAE_USUARIO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.AlertaEntity", b =>
                {
                    b.HasOne("Global_Solution.Domain.Entities.AreaRiscoEntity", "AREA_RISCO")
                        .WithMany("ALERTAS")
                        .HasForeignKey("ID_AREA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Global_Solution.Domain.Entities.LeituraSensorEntity", "LEITURA_GATILHO")
                        .WithMany()
                        .HasForeignKey("ID_LEITURA_GATILHO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AREA_RISCO");

                    b.Navigation("LEITURA_GATILHO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.InscricaoAlertaEntity", b =>
                {
                    b.HasOne("Global_Solution.Domain.Entities.AreaRiscoEntity", "AREA_RISCO")
                        .WithMany("INSCRICOES")
                        .HasForeignKey("ID_AREA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Global_Solution.Domain.Entities.UsuarioEntity", "USUARIO")
                        .WithMany("INSCRICOES")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AREA_RISCO");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.LeituraSensorEntity", b =>
                {
                    b.HasOne("Global_Solution.Domain.Entities.SensorEntity", "SENSOR")
                        .WithMany("LEITURAS")
                        .HasForeignKey("ID_SENSOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SENSOR");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.NotificacaoEntity", b =>
                {
                    b.HasOne("Global_Solution.Domain.Entities.AlertaEntity", "ALERTA")
                        .WithMany()
                        .HasForeignKey("ID_ALERTA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Global_Solution.Domain.Entities.UsuarioEntity", "USUARIO")
                        .WithMany("NOTIFICACOES")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ALERTA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.SensorEntity", b =>
                {
                    b.HasOne("Global_Solution.Domain.Entities.AreaRiscoEntity", "AREA_RISCO")
                        .WithMany("SENSORES")
                        .HasForeignKey("ID_AREA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AREA_RISCO");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.AreaRiscoEntity", b =>
                {
                    b.Navigation("ALERTAS");

                    b.Navigation("INSCRICOES");

                    b.Navigation("SENSORES");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.SensorEntity", b =>
                {
                    b.Navigation("LEITURAS");
                });

            modelBuilder.Entity("Global_Solution.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("INSCRICOES");

                    b.Navigation("NOTIFICACOES");
                });
#pragma warning restore 612, 618
        }
    }
}
